parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.3'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        port: '5432'
        host: 'pgsql'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
