version: '3.7'

services:
  pgsql:
    image: postgres:11.3
    environment:
      - TZ=Europe/Minsk
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: >
      postgres
        -c listen_addresses=*
    volumes:
      - pgdata_11_3:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/fpm.Dockerfile
    depends_on:
      - pgsql
    volumes:
      - ./:/var/www/app.loc:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
      PHP_IDE_CONFIG: serverName=app

  php-cli:
    build:
      context: .
      dockerfile: ./docker/php/cli.Dockerfile
    depends_on:
      - pgsql
    volumes:
      - ./:/var/www/app.loc:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT}
      PHP_IDE_CONFIG: serverName=simple-app
    tty: true

  nginx:
    image: nginx:1.15.11
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app.loc:delegated
    links:
      - php-fpm
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_PORT}:8001"

volumes:
  pgdata_11_3: